# Variable assignment

As briefly explained in the last notebook, you will often want to save data as variables. Variables are named data obects that allow you to save data inside of Python's memory. They are case sensitive and should ideally contain a brief description of their contents. They are case sensitive and should not begin with a number or a symbol.

Names should be **unique**. If you reuse an old name, its definition will be overwritten!  

Keep in mind this three-piece recipe: 

* The **variable name** goes on the _LEFT SIDE_
* The **equals sign** `=` goes in the _MIDDLE_
* The variable's **definition** goes on the _RIGHT SIDE_

**HINT**: You also learned that text data should always be wrapped in quotations (single? double?)

We want to save data inside of variables in Python because we can then manipulate those variables to perform complex tasks!

We also want to utilize a few built-in functions to figure out the data 

- The `pwd` function will show you the file pate to your working directory (more on this in Week2).  
- `ls` returns the contents of your working directory.  
- `del` deletes a single variable.  
- `%who` will show you variables you have defined in your global environment.

In [13]:
pwd # print working directory

'/Users/evan.admin/Desktop/DIGHUM101/Week1'

In [2]:
ls # list contents of working directory

1-1_JupyterNotebooks.ipynb
1-2_VariableAssignment_Types_Structures.ipynb
1-3_Tables.ipynb
1-4_WorkingWithStrings.ipynb
img/
iris.csv
poe.txt


In [4]:
Name = "Evan"

In [6]:
City = "Berkeley"

In [7]:
%who

City	 Name	 


In [8]:
del(Name) 

# Challenge 1
1. Define a variable named Name that stores your name.  
2. Define a variable named Age that stores your age.  
3. Define a variable named City that stores your hometown.  

In [17]:
print(5 + 5)

10


In [16]:
print("5" + "5")

55


In [3]:
## YOUR CODE HERE
Name = "Evan"
Age = 36
City = "Lansing, MI"

In [15]:
%who

Age	 City	 Name	 


Read and run the cell below to see how we can combine different values in expressions:

In [31]:
# 4. What is the function in the below line of code? How many arguments are there? (hint: they are separated by commas)
print(Name, "is", Age, "years old", "and is from " + City + ".")

Evan is 36 years old and is from Lansing, MI.


In [2]:
# 5. Why does the following line of code return an error message? 
# hint: this is actually a super helpful error message!
# What is Samantha? Why is it "not defined"?

Samantha = 5
Name = Samantha
print(Name)

5


# Data types

So far we have seen a few examples with floats, integers, strings, and logical types. The type of data is important because **types control what operations can be done on values**!

We can use the `type` function to check the type/class of some data!

In [4]:
# string data (character/text data)
type(Name)

str

We will discuss this more in a later notebook, but know that strings have methods that can be accessed by typing a period after the name of your string variable. 

Type Name. and then press the tab key so that the list of methods appears. What do you think ".upper" will do? Try it! 

In [9]:
Sentence = "The cat jumped over the dog when the dog jumped over the mouse"
Sentence = Sentence.lower()

In [10]:
print(Sentence)

the cat jumped over the dog when the dog jumped over the mouse


In [11]:
# floating point numbers (decimals)
type(3.14)

float

In [12]:
# integers (positive and negative whole numbers including zero)
type(5)

int

In [13]:
type(100000000.0)

float

In [15]:
# boolean True and False logical values
type(False)

bool

In [17]:
False + True

1

# Getting help

To get help for a method, type `help(object_name.method_name)`. 

For example, if I want to get help with `.upper`, type: 

In [19]:
help(Name.lower)

Help on built-in function lower:

lower(...) method of builtins.str instance
    S.lower() -> str
    
    Return a copy of the string S converted to lowercase.



Alternatively, you can type a question mark after a built-in function to see its help page:

In [22]:
abs(-10)

10

# Challenge 2

Why does the following code produce an error?

In [25]:
print("Hello World!")

# this error message is pretty vague...

Hello World!


And this one?

In [28]:
print("I am ", 27, " years old.")

# this error message is actually pretty helpful! 

I am  27  years old.


# Data type conversion

Converting data types is also very important. In the second part of Challenge 2 above, the integer 27 breaks the code because it needs to first be converted ("coerced") to string type. 

After we go through the cells below, return to the problem above and fix the error message by converting 27 to a string. Also, can you think of any other ways besides plus symbols to fix this code? 

Let's see what happens when we try to convert the following values:

In [29]:
print(Name)
print(Age)
print(City)

Evan
36
Lansing, MI


In [31]:
# convert Age to a string using `str`!
Age_str = str(Age)
Age_str = "36"
print(Age_str)
print(type(Age_str))

36
<class 'str'>


In [32]:
# convert the integer Age to a float
print(type(Age))
Age_float = float(Age)
print(Age_float)
print(type(Age_float))

<class 'int'>
36.0
<class 'float'>


In [33]:
# convert boolean True and False to integers
print(type(True))
print(type(False))

bool_int_T = int(True)
bool_int_F = int(False)

print(bool_int_T)
print(bool_int_F)
print(type(bool_int_T))
print(type(bool_int_F))

<class 'bool'>
<class 'bool'>
1
0
<class 'int'>
<class 'int'>


In [37]:
str_int = float("5000.34")
print(str_int)

5000.34


In [34]:
# convert a string to an integer! (what happened?)
str_int = int(Name)
print(str_int)

ValueError: invalid literal for int() with base 10: 'Evan'

# Challenge 3

Remember that the order in which you program your code affects how it is output. Without running any code, what is the output of the print statement below?

In [42]:
initial = "left"  
position = initial + " " + "of" + " " + "center"
initial = "right" + "center"
print(position)  

left of center


# Indexing

In Python programming, order matters (note: dictionaries are the main exception). This allows us to reference certain parts of a piece of data by its position, or index. 

Use bracket notation `[ : ]` to tell Python what parts of a piece of data (which "slice") you want. The number to the left side of the colon is the start point and the number to the right is the _excluded end point_. 

In [43]:
Name2 = "Isabel Allende"
print(Name2)

Isabel Allende


What if we just want to index the third letter?

In [47]:
Name2[4]

# wait, the number 2 gets us the third letter?

'e'

What if we just want the first name? We can use the character positions to reference only the first _five_ characters:

In [52]:
first_name = Name2[0:6]
print(first_name)
first_name

Isabel


'Isabel'

**Whoa!** _What is happening here?!_ Note that the letter "I" is indexed by the 0th position! 

This is because you do not have to move at all to reference the first letter - you are already at the first character! 

Thus, Python is said to be a **_zero-indexed language_** - the first element in a string or a list is the 0th element. 

In [51]:
# how about this - what changed compared to Name[0:6]?
first_name = Name2[:7]
print(first_name)
first_name

Isabel 


'Isabel '

In [ ]:
Isabel Allende

In [53]:
# You can also go every second character ("stride")!
stride_name = Name2[::2]
print(stride_name)

Iae led


In [54]:
# ... or every third!
stride_name2 = Name2[::3]
print(stride_name2)

Ib ld


# Challenge 4

Save the title of your favorite movie inside of a variable named "movie". 

1. Index just the first letter.  
2. Index only the fourth letter.  
3. Index the first two letters.  
4. Index the last three letters (hint: use the `len` function to find out how many characters are in the title of your movie)
5. Using your intuition, can you guess how to backwards stride?

In [66]:
## YOUR CODE HERE

movie = "Mission Impossible"
print(movie)
print(movie[0])
print(movie[:2])

print(len(movie))

print(movie[15:])
print(movie[len(movie) - 3 : len(movie)])

Mission Impossible
M
Mi
18
ble
ble


In [1]:
Name = "Aoki"
print(Name)

Aoki


In [3]:
Name.upper()

'AOKI'

# Data structures

Although storing single numbers and names within variables is fine, we often want to store more than one thing! In reality, we will eventually want to store large amounts of complex data within single variables. These data are generally organized into the following structures in Python. 

1. Strings
2. Lists
3. Arrays
4. Dictionaries
5. Tuples

You've seen a little about how strings work (recall that they have "methods") and we will focus on them in later notebooks. However, it is important to spend some time covering lists and arrays. 

Dictionaries are also important, as they _contain unordered key/value pairs_ as are tuples (immutable lists), but more on these later. 

### Lists
Lists are useful when you want to store more than one thing inside of a variable. These values can be of different data types. 

Make a list by separating values by commas within brackets.  

Add your favorite food to the end of your Name, Age, and City. Thus, your list should have four elements:

In [17]:
Name = "Evan"
Age = 36
City = "Lansing, MI"

In [18]:
my_list = [Name, Age, City, "Sushi"]
print(my_list)

['Evan', 36, 'Lansing, MI', 'Sushi']


**NOTE**: like strings, lists have methods that are also called by typing a period after the name of your variable!

Now, add your major using the `.append` method:

In [19]:
my_list.append("Anthropology")

print(my_list)

['Evan', 36, 'Lansing, MI', 'Sushi', 'Anthropology']


# Challenge 5
1. Using what you know about indexing single values, how do you overwrite your favorite food with your favorite beverage?

In [20]:
## YOUR CODE HERE
my_list[3] = "coffee"
print(my_list)

['Evan', 36, 'Lansing, MI', 'coffee', 'Anthropology']


In [21]:
my_list[0] = "Doug"
print(my_list)

['Doug', 36, 'Lansing, MI', 'coffee', 'Anthropology']


In [23]:
5 + 5

10

In [24]:
"5" + "5"

'55'

In [25]:
print(Name)

Evan


In [22]:
type(my_list)

list

### Arrays

Lists are called arrays when they are of the same type! Arrays are preferred to lists when handling large amounts of data because they are computationally more efficient.

In [30]:
!pip install numpy
import numpy as np

In [31]:
my_array = np.array([4,5,6, 10000])

print(my_array)
print(type(my_array))

[    4     5     6 10000]
<class 'numpy.ndarray'>


In [32]:
number_range = np.arange(14,29)
print(number_range)

[14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]


In [34]:
# what if I want just the third, fourth and fifth elements of "number_range"
number_range[2:5]

array([16, 17, 18])

In [35]:
list_of_lists = [[3,3,2],["Evan", "Anthropology"],[True, False]]
print(list_of_lists)

[[3, 3, 2], ['Evan', 'Anthropology'], [True, False]]


### Dictionaries
Dictionaries contain unordered key/value pairs. 

In [46]:
my_dictionary = {"Name": "Evan", 
                 "Age":[27,36.5, True], 
                 "City": "Lansing", 
                 "Favorite food": "Sushi",
                 "Major": "Anthropology",
                 "Hungry": True, 
                 "Height": 1.88
                }
print(my_dictionary)

{'Name': 'Evan', 'Age': [27, 36.5, True], 'City': 'Lansing', 'Favorite food': 'Sushi', 'Major': 'Anthropology', 'Hungry': True, 'Height': 1.88}


So, if I just want to see the Favorite food from this dictionary, I can type: 

In [37]:
my_dictionary["Favorite food"]

'Sushi'

In [47]:
my_dictionary["Age"]

[27, 36.5, True]

### Tuples
Tuples are similar to lists and arrays, but they are unchangeable ("immutable"). 

For example, we cannot change the output of 10 (the dividend) divided by 3 (the divisor) - by definition the quotient is 3 and the remainder is 1. 

In [48]:
div = divmod(10,3)
print(div)
print(type(div))

(3, 1)
<class 'tuple'>


# Logical operators

Logical operators help us make comparisons between things! Are two things equal/equivalent? Is one thing larger or smaller than another thing? 

In [60]:
# == (is equal to)
False == False

True

In [61]:
# >, <, >=, <= (greater than/less than, equal to)
print(3 < 5)
print(3 > 5)
print(4 >= 4)
print(5 <= 4)

True
False
True
False


In [63]:
# != (not equal to)
print(5 != 4)

True


# Challenge 5

Syntax is very important to programming. Computers expect us to enter input in a highly specified way. 

Why does the following code fail? What is it probably supposed to do, and what is it actually doing?

In [65]:
age = 31
print(age)

31


and

In [66]:
31 = age

SyntaxError: can't assign to literal (<ipython-input-66-0f5e90d26c19>, line 1)